/**
 * The question definitions, as the browser receives them.
 *
 * A declaration and not a module: the code it describes is generated by
 * `build/client.ts`'s `schemaModule` and written to `assets/js/schema.js`, because the
 * definitions live in `src/questions` and the client cannot reach them any other way.
 * `connect-src 'none'` (docs/decisions/0006, 0007 · C1) forbids fetching
 * `/questions.json` from a page, so the schema arrives as script instead —
 * docs/decisions/0015 records the choice, and `import.ts` records the state of affairs
 * before it ("the client has no copy of the question set").
 *
 * `buildClient` skips `.d.ts` deliberately, so this file types the import and the
 * generated module supplies the values. The `Worksheet` type is imported from the
 * definitions themselves rather than restated here: a second description of the same
 * shape is the drift docs/decisions/0015 spends its length arguing against.
 *
 * Import it as `./schema.js`. Every other client import says `.ts` because a source file
 * exists to point at; this one does not, and `nodenext` resolution finds this declaration
 * from the `.js` specifier the browser will actually request.
 */

import type { Worksheet } from "../questions/index.ts";

export declare const WORKSHEETS: readonly Worksheet[];
